"""macro_indicators

Revision ID: 2dea57e84dfe
Revises: 60c1465028e2
Create Date: 2026-07-21 14:45:59.922533
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2dea57e84dfe'
down_revision: str | None = '60c1465028e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'as_of', 'source', name='uq_macro_name_asof_source')
    )
    op.create_index(op.f('ix_macro_indicators_as_of'), 'macro_indicators', ['as_of'], unique=False)
    op.create_index(op.f('ix_macro_indicators_name'), 'macro_indicators', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macro_indicators_name'), table_name='macro_indicators')
    op.drop_index(op.f('ix_macro_indicators_as_of'), table_name='macro_indicators')
    op.drop_table('macro_indicators')
    # ### end Alembic commands ###
