"""article_tickers

Revision ID: bbba385fe7b9
Revises: 2dea57e84dfe
Create Date: 2026-07-21 18:45:05.382443
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'bbba385fe7b9'
down_revision: str | None = '2dea57e84dfe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('tickers', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'tickers')
    # ### end Alembic commands ###
