"""content broll meta

Revision ID: 7598c32287dd
Revises: aa3ccec70626
Create Date: 2026-07-22 12:12:48.504047
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7598c32287dd'
down_revision: str | None = 'aa3ccec70626'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('broll_source_url', sa.String(length=500), nullable=True))
    op.add_column('contents', sa.Column('broll_author', sa.String(length=200), nullable=True))
    op.add_column('contents', sa.Column('broll_license', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'broll_license')
    op.drop_column('contents', 'broll_author')
    op.drop_column('contents', 'broll_source_url')
    # ### end Alembic commands ###
